language: php
php:
  - "7.2"
install:
  - composer install
script:
  - composer phpunit:coverage
  - composer phpstan
  - composer phpcs
  - composer phpmd
before_script:
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
